"""budget alerts and rate limits

Revision ID: 3275d3d47bb8
Revises: db6313b997ee
Create Date: 2026-10-01 15:39:40.674746

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "3275d3d47bb8"
down_revision: str | None = "db6313b997ee"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rate_limits",
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "budget_alerts",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.Column("month", sa.CHAR(length=7), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("category_id", "month"),
    )
    op.create_index(op.f("ix_budget_alerts_user_id"), "budget_alerts", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_budget_alerts_user_id"), table_name="budget_alerts")
    op.drop_table("budget_alerts")
    op.drop_table("rate_limits")
    # ### end Alembic commands ###
